// ui/src/Up.vue
<template>
  <div v-on:drop="drop" v-on:dragover="dragOver" v-on:mouseout="mouseOut">
    <h2>Enter Text or Drag and Drop a File</h2>
    <Editor></Editor>

    <button class="paste" v-on:click="upload">Paste</button>
  </div>
</template>

<script>
import axios from 'axios';

import Editor from './Editor.vue';

export default {
  data() {
    return {
      text: ''
    }
  },
  created() {
    this.$root.$on('editor-change', text => {
      this.text = text;
    });
  },
  methods: {
    drop(e) {
      e.preventDefault();
      
      const files = e.dataTransfer.files;
      
      if (files.length === 1) {
        const file = files[0];
        axios.post(`${API_URL}`, file)
          .then(res => {
            window.location = res.data;
          })
          .catch(err => {
            console.error(err);
          });
      }
    },
    dragOver(e) {
      e.preventDefault();
    },
    mouseOut(e) {
      e.preventDefault();
    },
    upload() {
      axios.post(`${API_URL}`, this.text)
        .then(res => {
          window.location = res.data;
        })
        .catch(err => {
          console.error(err);
        });
    }
  },
  components: {
    Editor
  }
};
</script>

<style scoped>
.paste {
  margin-top: 16px;
  padding: 8px 16px;

  color: #fff;
  font-size: 15px;
  font-family: 'Roboto', sans-serif;
  font-weight: 700;

  background-color: #0389ff;

  outline: 0;
  border: none;
  border-radius: 2px;

  cursor: pointer;
}
</style>

// ui/src/Up.jsx
import styles from './up.css';

import React, { Component } from 'react';

import Editor from './Editor';

import axios from 'axios';

export default class Up extends Component {
  constructor(props) {
    super(props);

    this.state = {
      text: ''
    };

    this.onDrop = this.onDrop.bind(this);
    this.onDragOver = this.onDragOver.bind(this);
    this.onMouseOut = this.onMouseOut.bind(this);
    this.onTextUpdate = this.onTextUpdate.bind(this);
    this.upload = this.upload.bind(this);
  }

  onDrop(event) {
    event.preventDefault();
    
    const files = event.dataTransfer.files;
    
    if (files.length === 1) {
      const file = files[0];
      axios.post(`${API_URL}`, file)
        .then(res => {
          window.location = res.data;
        })
        .catch(err => {
          console.error(err);
        });
    }
  }

  onDragOver(event) {
    event.preventDefault();
  }

  onMouseOut(event) {
    event.preventDefault();
  }

  onTextUpdate(text) {
    this.setState({
      text
    });
  }

  upload(event) {
    axios.post(`${API_URL}`, this.state.text)
      .then(res => {
        window.location = res.data;
      })
      .catch(err => {
        console.error(err);
      });
  }

  render() {
    return (
      <div onDrop={this.onDrop} onDragOver={this.onDragOver} onMouseOut={this.onMouseOut}>
        <h2>Enter Text or Drag and Drop a File</h2>
        <Editor onTextUpdate={this.onTextUpdate} />

        <button className={styles.paste} onClick={this.upload}>Paste</button>
      </div>
    );
  };
}
