// ui/src/View.jsx
import React, { Component } from 'react';

import ViewText from './ViewText';

import axios from 'axios';

export default class View extends Component {
  constructor(props) {
    super(props);

    this.state = {
      loaded: false,
      mimeType: null,
      data: null
    };
  }

  componentDidMount() {
    const { objectId } = this.props.match.params;

    axios.get(`${API_URL}/${objectId}`)
      .then(res => {
        const mimeType = res.headers['content-type'];

        this.setState({
          mimeType: mimeType,
          data: res.data,
          loaded: true
        });
      })
      .catch(err => {
        console.error(err);
      });

    console.log('object ID is ' + objectId);
  }

  render() {
    let content = null;
    if (this.state.loaded) {
      content = (
        <ViewText text={this.state.data} />
      );
    }

    return (
      <div>
        {content}
      </div>
    );
  };
}

// ui/src/View.vue
<template>
  <div v-if="this.loaded">
    <ViewText v-bind:text="this.data" v-bind:mime-type="this.mimeType"></ViewText>
  </div>
</template>

<script>
import ViewText from './ViewText.vue';

import axios from 'axios';

export default {
  data() {
    return {
      loaded: false,
      mimeType: null,
      data: null
    };
  },
  created() {
    const { objectId } = this.$route.params;

    axios.get(`${API_URL}/${objectId}`)
      .then(res => {
        const mimeType = res.headers['content-type'];

        this.mimeType = mimeType;
        this.data = res.data;
        this.loaded = true;
      })
      .catch(err => {
        console.error(err);
      });

    console.log('object ID is ' + objectId);
  },
  components: {
    ViewText
  }
}
</script>

<style scoped>

</style>
